# Generated by Django 2.2.2 on 2020-04-09 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waveforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('com_version', models.CharField(max_length=32)),
                ('time_tamp', models.CharField(max_length=32)),
                ('gain', models.CharField(max_length=32)),
                ('temperature', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('data_len', models.IntegerField()),
                ('thickness', models.FloatField(blank=True, null=True)),
                ('network_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='GWS.Sensor', to_field='network_id')),
            ],
        ),
    ]
