# Generated by Django 2.2.2 on 2020-04-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0002_waveforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waveforms',
            name='network_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GWS.Sensor', to_field='network_id'),
        ),
    ]
