# Generated by Django 2.2.2 on 2020-04-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0003_auto_20200409_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='delete_status',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
