# Generated by Django 2.2.2 on 2020-04-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0004_sensor_delete_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor_status',
            new_name='sensor_run_status',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_online_status',
            field=models.SmallIntegerField(choices=[(0, '离线'), (1, '在线')], default=1),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gw_status',
            field=models.SmallIntegerField(choices=[(0, '离线'), (1, '在线')], default=1),
        ),
    ]
