# Generated by Django 2.2.2 on 2020-04-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0006_auto_20200416_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='enterprise',
            new_name='Enterprise',
        ),
    ]
