# Generated by Django 2.2.2 on 2020-04-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0008_corrosion_rate_corrosion_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
