# Generated by Django 2.2.2 on 2020-04-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0010_sensor_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.SmallIntegerField(choices=[(0, 'ETM-100')], default=0),
        ),
    ]
