# Generated by Django 2.2.2 on 2020-04-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0011_auto_20200417_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='alarm_temperature',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
