# Generated by Django 2.2.2 on 2020-04-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0012_sensor_alarm_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='alarm_corrosion',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
