# Generated by Django 2.2.2 on 2020-04-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0013_sensor_alarm_corrosion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='alarm_battery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='alarm_corrosion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='alarm_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='alarm_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='initial_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
