# Generated by Django 2.2.2 on 2020-04-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0015_sensor_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='battery',
            field=models.CharField(default=100, max_length=32),
        ),
    ]
