# Generated by Django 2.2.2 on 2020-04-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0016_auto_20200422_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='alarm_battery',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='alarm_corrosion',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='alarm_temperature',
            field=models.FloatField(default=310),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='alarm_thickness',
            field=models.FloatField(default=8),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='initial_thickness',
            field=models.FloatField(default=10),
        ),
    ]
