# Generated by Django 2.2.2 on 2020-05-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0017_auto_20200422_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='temperature',
        ),
        migrations.AddField(
            model_name='sensor',
            name='latitude',
            field=models.FloatField(default=31.293664),
        ),
        migrations.AddField(
            model_name='sensor',
            name='longitude',
            field=models.FloatField(default=120.775213),
        ),
    ]
