# Generated by Django 2.2.2 on 2020-05-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0018_auto_20200507_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='latitude',
            field=models.FloatField(blank=True, default=31.293664, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='longitude',
            field=models.FloatField(blank=True, default=120.775213, null=True),
        ),
    ]
