# Generated by Django 2.2.2 on 2020-05-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0019_auto_20200507_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
