# Generated by Django 2.2.2 on 2020-05-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0020_auto_20200507_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
