# Generated by Django 2.2.2 on 2020-05-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0022_auto_20200508_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Enterprise',
            field=models.CharField(max_length=64),
        ),
    ]
