# Generated by Django 2.2.2 on 2020-06-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWS', '0028_auto_20200512_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('sound_V', models.IntegerField()),
                ('temperature_co', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='sensor',
            name='material',
            field=models.SmallIntegerField(default=1),
        ),
    ]
